name: Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: echo ${{ secrets.MY_SECRET }} > test; cat test
